-- +micrate Up
-- SQL in section 'Up' is executed when this migration is applied

create type field_kind as enum('text', 'number', 'email', 'date', 'boolean',
  'captcha', 'options', 'phone', 'password', 'url');

create table page_field (
  id bigint not null primary key generated by default as identity,
  page_id bigint not null references page_page(id),
  title varchar(100) not null,
  kind field_kind not null default 'text',
  deleted_at timestamp without time zone null,
  created_at timestamp without time zone not null default now(),
  updated_at timestamp without time zone not null default now()
);

-- +micrate Down
-- SQL section 'Down' is executed when this migration is rolled back

drop type field_kind;
drop table page_field;
