-- +micrate Up
-- SQL in section 'Up' is executed when this migration is applied

create table users(
  id bigint not null primary key generated by default as identity,
  email varchar(100) not null unique,
  password varchar(100) null,
  deleted_at timestamp without time zone null,
  created_at timestamp without time zone not null default now(),
  updated_at timestamp without time zone not null default now()
);

-- +micrate Down
-- SQL section 'Down' is executed when this migration is rolled back

drop table users;
