-- +micrate Up
-- SQL in section 'Up' is executed when this migration is applied

create table permission (
  id bigint not null primary key generated by default as identity,
  user_id bigint not null references "user"(id),
  project_id bigint not null references project(id),
  admin bool not null default false,
  starts_at timestamp without time zone null,
  deleted_at timestamp without time zone null,
  created_at timestamp without time zone not null default now(),
  updated_at timestamp without time zone not null default now()
);

-- +micrate Down
-- SQL section 'Down' is executed when this migration is rolled back

drop table permission;
