-- +micrate Up
-- SQL in section 'Up' is executed when this migration is applied

create table page_option (
  id bigint not null primary key generated by default as identity,
  field_id bigint not null references page_field(id),
  content varchar(250) not null,
  deleted_at timestamp without time zone null,
  created_at timestamp without time zone not null default now(),
  updated_at timestamp without time zone not null default now()
);

-- +micrate Down
-- SQL section 'Down' is executed when this migration is rolled back

drop table page_option;
